preload = /home/vixel/Pictures/wallpapers/windows-error.jpg

# Leaving the monitor name empty (just a comma) works as a wildcard
wallpaper = eDP-1,/home/vixel/Pictures/wallpapers/windows-error.jpg

splash = false
